# Assignment 1

## Question 1

### A program to simulate random walks.

A particle is positioned at each of the (x, y) coordinates of a N x N lattice grid.
M simualtions are carried out to determine the probability of each particle reaching
the bottom boundary of the grid during a random walk of up to S steps.

This is a compute bound problem, as there is no data shared between simulations.
The result of each simualtion is independent and the result is success (if the bottom
boundary is reached) or failure (if any other boundary is reached, or S steps are
completed without a boundary being reached). A data structure is used to count the
number of successes, which is subsequently turned into a probability.

This is an integer problem. The random walks are implemented as a single integer
step up, down, left or right. And the success counts are integer. Therefore, to avoid
floating point overhead, as much as possible is done using integer data
structures (which also results in a memory saving) and integer operations. A floating
point data sructure is used at the end of the program to store the probabilties.

Numpy arrays are used at the outset as the data structure to store the random walk
success counts (an integer array) and the resulting probabilities (a float array). 
Matplotlib is then used to display the probabilities.

#### Program Structure Optimisation

Because this is a compute bound problem, the structure of the program was consisdered
carefully to ensure function calls and repeated operations are minimised. Function calls
considered likely to be expensive are done once outside of a loop rather than multiple
times inside a loop.

Let's go...

#### Import required libraries

In [1]:
import matplotlib.pyplot as plt
import numpy as np
import random
import time


In [2]:
class Timer:    
    def __enter__(self):
        self.start = time.time()
        return self

    def __exit__(self, *args):
        self.end = time.time()
        self.interval = self.end - self.start


Define global variables

In [3]:
# Number of trials. The same number of trials is conducted for each grid point.

M = 1000

# Grid size, N x N

N = 100

# The maximum number of random walk steps.

S = N * N  # TODO: Sensible?


Define Numpy arrays to store the number of trial successes (particle hits bottom boundary), and subsequently the probability of success.


In [4]:
# Successes are integers, so use uint32 to save some memory and minimise cache misses. 

successes  = np.zeros((N, N), dtype='uint32')

# Probabilities are calculated at the end of the program to avoid floating point overhead.

probabilities = np.zeros((N, N))


In [5]:
print(successes)


[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [6]:
def random_walk(x, y):
    """
    This function takes as input the (x, y) position of a particle on an N x N grid, and then
    takes up to S random walk steps up, down, left or right. The function returns True if the
    bottom boundary is reached, or the bottom boundary is the initial position. The function
    returns False if S steps are taken and no boundary is reached, or as soon as the
    top, left or right boundarie are reached.
    """
 
    # Parameter sanity checks...
    
    assert x >= 1 and x <= N, "x bound error"
    assert y >= 1 and y <= N, "y bound error"
    
 
    # If the intial position of the particle is on a boundary, no need to start a random walk.
    # The order of tests selected to return True as soon as possible.
    
    if y == 1: return True  # Bottom   
    if y == N: return False # Top    
    if x == 1: return False # Left    
    if x == N: return False # Right
    

    # Store initial (x, y) position...
    
    new_x = x
    new_y = y
    

    # Start the random walk...
    
    for s in range(S):
    
        # Define the following...
        
        # 1 == down
        # 2 == up
        # 3 == left
        # 4 == right
    
        direction = random.randint(1, 4)
        
        # Sanity check...
        
        assert direction >= 1 and direction <= 4
 
        # Walk, and test for boundary conditions as soon as possible...

        if direction == 1:
            new_y -= 1
            if new_y == 1:
                return True

        if direction == 2:
            new_y += 1
            if new_y == N:
                return False
            
        if direction == 3:
            new_x -= 1
            if new_x == 1:
                return False

        if direction == 4:
            new_x += 1
            if new_x == N:
                return False
    

    # Boundary not reached...
    
    return False


In [7]:
# Run M random walk simualtions on each (x, y) grid position.

# NB We are using (1..N, 1..N) as (x, y) coordinates in a Cartesian sense, but Numpy
# uses [row, column] starting in the top left. So, some jiggery pokery is
# required to make the Numpy array look like a Cartesian array.

with Timer() as t:
    
    for m in range(M):
        for x in range (1, N + 1):
            for y in range (1, N + 1):
                if random_walk(x, y):
                    successes[x - 1, y - 1] += 1 # TODO: Jiggery pokery! Or, do it in Matplotlib later?
                
    probabilities = successes / M

print("Total time: {0}".format(t.interval))


KeyboardInterrupt: 

In [ ]:
print(successes)


In [ ]:
print(probabilities)


In [ ]:
plt.matshow(probabilities)


## Question 2