# Techniques of High Performance Computing - Assignment 2

### Name: John Duffy

### Student Number: 19154676

In [ ]:
# Import libraries common to Questions 1 & 2.

import numpy as np
import pyopencl as cl

# Question 1

## OpenCL CSR Matrix-Vector Product

### Program Description

This program...

In [ ]:
from scipy.sparse.linalg import LinearOperator

In [117]:
# Define the class CSR which is a subclass of LinearOperator.

class CSR(LinearOperator):
    """
    This class... 
    """
    
    def __init__(self, data, indices, indptr):
        """
        """
        self.data = data
        self.indices = indices
        self.indptr = indptr
        self.shape = (2, 2)
    
    def _matvec(self, x):
        """
        """
        
        # Non-OpenCL matrix-vector product algorithm.
        
        
        
        
        return np.ones(2)

In [118]:
# Test an instance of CSR.

a = scipy.sparse.csr_matrix([[2,0], [0,2]])

csr = CSR(a.data, a.indices, a.indptr)

csr.matvec([1,1])

array([1., 1.])

In [119]:
csr*np.ones((2))

array([1., 1.])

In [107]:
a = scipy.sparse.csr_matrix(np.ones((3,3)))

In [108]:
a.data

array([1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [109]:
a.indptr

array([0, 3, 6, 9], dtype=int32)

In [110]:
a.indices

array([0, 1, 2, 0, 1, 2, 0, 1, 2], dtype=int32)

In [111]:
b = np.ones((2,2))

In [112]:
b.dtype

dtype('float64')

In [113]:
b.flatten()

array([1., 1., 1., 1.])

In [ ]:
pyopencl.VERSION

In [ ]:
pyopencl.get_cl_header_version()

In [ ]:
pyopencl.get_platforms()

In [ ]:
platforms = pyopencl.get_platforms()

In [ ]:
for p in platforms:
    devices = p.get_devices()
    
devices
    


# Question 2

## Solving a Poisson Problem with OpenCL

### Program Description

This program...

In [ ]:
from scipy.sparse.linalg import cg 