# Techniques of High Performance Computing - Assignment 2

### Name: John Duffy

### Student Number: 19154676

In [2]:
# Import libraries common to Questions 1 & 2.

import numpy as np
import pyopencl as cl

# Question 1

## OpenCL CSR Matrix-Vector Product

### Program Description

This program...

### Optimisation Results

A class LinearOperatorBaseline was created to use as a baseline for measuring the performance gains through subsequnt use of OpenCL and AVX2.

In [71]:
from scipy.sparse import csr_matrix, eye
from scipy.sparse.linalg import LinearOperator

In [72]:
# Define the class LinearOperatorBaseline for baseline performance measurements.

class LinearOperatorBaseline(LinearOperator):
    """
    This class... 
    """
    
    def __init__(self, data, indices, indptr):
        """
        """
        self.data = data
        self.indices = indices
        self.indptr = indptr
        self.shape = (len(indptr) - 1, len(indptr) - 1)  # Assume square.
    
    def _matvec(self, x):
        """
        """
        y = np.zeros(x.shape[0], dtype=np.float64)
        
        for i in range(self.shape[1]): 
            y[i] = np.dot(self.data[self.indptr[i]:self.indptr[i + 1]], x[self.indices[self.indptr[i]]:self.indptr[i + 1]])
            
        return y

In [77]:
# Create a test instance of LinearOperatorBaseline.

N = 1000000

csr = eye((N), dtype=np.float64).tocsr()

linear_operator = LinearOperatorBaseline(csr.data, csr.indices, csr.indptr)

v = np.full((N), 2)

In [78]:
%%timeit

linear_operator.matvec(v)

2.32 s ± 15.9 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [79]:
%%timeit

linear_operator * v

2.29 s ± 17.7 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [80]:
linear_operator.matvec(v)

array([2., 2., 2., ..., 2., 2., 2.])

In [81]:
linear_operator * v

array([2., 2., 2., ..., 2., 2., 2.])

In [82]:
# Define the class LinearOperatorOpenCL.

class LinearOperatorOpenCL(LinearOperator):
    """
    This class... 
    """
    
    def __init__(self, data, indices, indptr):
        """
        """
        self.data = data
        self.indices = indices
        self.indptr = indptr
        self.shape = (len(indptr) - 1, len(indptr) - 1)  # Assume square.
    
    def _matvec(self, x):
        """
        """
        y = np.zeros(x.shape[0], dtype=np.float64)
        
        for i in range(self.shape[1]): 
            y[i] = np.dot(self.data[self.indptr[i]:self.indptr[i + 1]], x[self.indices[self.indptr[i]]:self.indptr[i + 1]])
            
        return y

In [83]:
# Create a test instance of LinearOperatorOpenCL.

N = 1000000

csr = eye((N), dtype=np.float64).tocsr()

linear_operator = LinearOperatorOpenCL(csr.data, csr.indices, csr.indptr)

v = np.full((N), 2)

In [84]:
%%timeit

linear_operator.matvec(v)

2.32 s ± 16.6 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [85]:
%%timeit

linear_operator * v

2.33 s ± 64.2 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [86]:
linear_operator.matvec(v)

array([2., 2., 2., ..., 2., 2., 2.])

In [87]:
linear_operator * v

array([2., 2., 2., ..., 2., 2., 2.])

# Question 2

## Solving a Poisson Problem with OpenCL

### Program Description

This program...

In [ ]:
from scipy.sparse.linalg import cg 